### ISSUE TITLE
Integrate Dark Mode

### ISSUE THREAD

**Issue by sethburtonhall** [drewclem/protege#227]
## Is your feature request related to a problem? Please describe.
No problem, just a way to improve the user's experience.

## Describe the solution you'd like
Give users the option to view the app in dark mode to better match their devices settings.

## Describe alternatives you've considered
We could support light mode only, but it could be a good opportunity to audit any styling concerns and look for ways to improve.

### Additional context
This is a joy to work with in [Tailwind](https://tailwindcss.com/docs/dark-mode)

**Comment by drewclem** [comment]
Closing this for now. I don't see the added benefit at the current moment.

**Comment by mkucko** [comment]
It's about preserving one's eyesight:
* in a poorly-lit room it's much easier to read white characters on a dark background (= dark mode)
* in a well-lit room it's much easier to read the default  - black letters on white background (= light mode)

Additionally, all your applications should be configured in the same way, otherwise it's even worse, switching contrasts like that back and for.
It would really be nice if Protege had that option, too

**Comment by vChavezB** [comment]
From a technical point of view ontologies wont benefit from a dark theme, axioms, assertions and swrl rules will still be the same. However as an ontologist it would be nice to have a dark theme for the sake of user experience.

Examples of software that use dark themes just to mention a few VS Code, Notepad++, Github, Gitlab.

**Comment by kuwv** [comment]
> Closing this for now. I don't see the added benefit at the current moment.

Can you reopen this please?

**Comment by riley-momo** [comment]
Another request to please open this issue. Especially considering protege web features dark mode, please bring parity to the desktop experience, which is required for more advanced use of protege.

**Comment by ugolafosse** [comment]
+1

**Comment by knight-captain** [comment]
There is a pull for this: 
https://github.com/protegeproject/protege/pull/1308
Hopefully that get's the OK, as the work has already been bone!
